import React from "react";
import hep from '../assets/images/hep.png'
import ov from '../assets/images/ov.png'
import sr from '../assets/images/sr.png'
import ncoe from '../assets/images/ncoe.png'
import fp from '../assets/images/fp.png'
import sa from '../assets/images/sa.png'
import acs from '../assets/images/acs.png'
import search from '../assets/images/search.png'
import infinity from '../assets/images/infinity.png'
import headsetsolid from '../assets/images/headset-solid.png'
function BenefitsOfZeroLoss() {

    return (
        <>
            {/* 3rd */}
            <section className='bg-[#040B0C] lg:py-[64px] py-[16px] lg:px-[0px] px-[25px]'>
                <div className='max-w-[1376px] mx-auto paddingmax'>
                    <h2 className='text-[#BAC9C5] text-center IBMPlexSansSemiBold lg:text-[40px] text-[18px] lg:leading-[48px] leading-[28px]'>Benefits of ZERO<span className='text-[#64B337]'>LOSS</span></h2>
                    <p className='max-w-[628.32px] pt-[12px] lg:leading-[24px] leading-[20px] lg:text-[16px] text-[14px] mx-auto text-center text-[#C4CBCB] IBMPlexSansRegular'>
                        Unlock exclusive benefits with Zeroloss: receive updates, access free content, enjoy top-tier support, and earn higher commissions.
                    </p>
                    <section className='pt-[56px]'>
                        <div className="grid items-start grid-cols-12 lg:gap-[32px]">
                            <div className="lg:col-span-4 lg:mt-[0px] mt-[16px] col-span-12 lg:h-full">
                                <div className='border  flex items-center justify-center lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                    <div className=''>
                                        <img src={hep} className='w-[85px]' />
                                        <h3 className='lg:text-[32px] text-[18px]  pt-[24px] lg:pt-[40px]  leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                            High Earning Potential
                                        </h3>
                                        <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                            Earn up to 20% in monthly recurring referral incentives based on the profits generated by the customers you refer. Each time they profit, you'll receive a consistent share, allowing you to build a reliable and growing income stream over time as your referred clients succeed.
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div className="lg:col-span-8  col-span-12">
                                <div className='border lg:mt-[0px] mt-[16px] lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                    <div className='lg:flex items-center'>
                                        <div className='lg:w-[120px]'>
                                            <img src={ov} className='w-[76px]' />
                                        </div>
                                        <div>
                                            <h3 className='lg:text-[32px] text-[18px] lg:pt-[0px] pt-[24px]  leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                                Ongoing Revenue
                                            </h3>
                                            <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] maw-w-[422px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                                Benefit from continuous earnings as long as your referrals remain active and profitable.                      </p>
                                        </div>
                                    </div>
                                </div>
                                <div className="grid items-start  grid-cols-12 lg:gap-[32px] lg:pt-[32px]">
                                    <div className="col-span-12 lg:mt-[0px] mt-[16px] lg:mt-[0px] mt-[16px] lg:col-span-6 lg:h-full">
                                        <div className='border lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                            <img src={sr} className='w-[51px]' />
                                            <h3 className='lg:text-[32px] text-[18px]  pt-[24px] lg:pt-[40px]  leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                                Supportive Resources
                                            </h3>
                                            <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                                Receive comprehensive support and marketing materials to help you succeed in your reseller efforts.                      </p>
                                        </div>
                                    </div>
                                    <div className="col-span-12 lg:mt-[0px] mt-[16px] lg:col-span-6 lg:h-full">
                                        <div className='border lg:mt-[0px] mt-[16px] lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                            <img src={infinity} className='w-[51px]' />
                                            <h3 className='lg:text-[32px] text-[18px]  pt-[24px] lg:pt-[40px]  leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                                No Cap on Earnings
                                            </h3>
                                            <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                                There’s no limit to how much you can earn; the more successful referrals you make, the higher your potential income.                      </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="grid items-start grid-cols-12 lg:gap-[32px] lg:pt-[32px]">
                            <div className="col-span-12 lg:col-span-5 lg:h-full">
                                <div className='border lg:mt-[0px] mt-[16px] lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                    <img src={search} className='w-[42px]' />
                                    <h3 className='lg:text-[32px] text-[18px]  pt-[40px]  leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                        Simple Tracking
                                    </h3>
                                    <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                        Access easy-to-use tools for tracking your referrals and managing your earnings. Stay updated with real-time insights, ensuring full control over your commissions at all times.
                                    </p>
                                </div>
                            </div>
                            <div className="col-span-12 lg:col-span-7 lg:h-full">
                                <div className='border lg:mt-[0px] mt-[16px] lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                    <img src={hep} className='w-[56px]' />
                                    <h3 className='lg:text-[32px] text-[18px]  pt-[24px] lg:pt-[40px]  leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                        Attractive Commission Structure
                                    </h3>
                                    <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                        Receive comprehensive support and marketing materials to help you succeed in your reseller efforts. Benefit from expert guidance and promotional resources designed to boost your sales and maximize your success.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div className="grid items-start grid-cols-12 lg:gap-[32px] lg:mt-[32px]">
                            <div className="col-span-12 lg:col-span-8">
                                <div className='border lg:mt-[0px] mt-[16px] lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                    <div className='lg:flex items-center'>
                                        <div className='lg:w-[180px]'>
                                            <img src={sa} className='w-[85px]' />
                                        </div>
                                        <div>
                                            <h3 className='lg:text-[32px] text-[18px]   leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                                Scalable Opportunities
                                            </h3>
                                            <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                                Grow your income potential significantly by expanding and enhancing your network of referred customers.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div className="grid items-start grid-cols-12 lg:gap-[32px] lg:pt-[32px]">
                                    <div className="col-span-12 lg:mt-[0px] mt-[16px] lg:col-span-6 lg:h-full">
                                        <div className='border lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                            <img src={fp} className='w-[60px]' />
                                            <h3 className='lg:text-[32px] text-[18px]  pt-[24px] lg:pt-[40px]  leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                                Flexible Partnership
                                            </h3>
                                            <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                                Join a Affliate program that aligns with your business goals and adapts to your selling strategy.
                                            </p>
                                        </div>
                                    </div>
                                    <div className="col-span-12 lg:col-span-6 lg:h-full">
                                        <div className='border lg:mt-[0px] mt-[16px] lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                            <img src={ncoe} className='w-[60px]' />
                                            <h3 className='lg:text-[32px] text-[18px]  pt-[24px] lg:pt-[40px]  leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                                No Cap on Earnings                      </h3>
                                            <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                                Benefit from clear and timely payment schedules with straightforward incentive calculations.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-span-12 lg:col-span-4 lg:h-full">
                                <div className='border lg:mt-[0px] mt-[16px] flex items-center justify-center lg:h-full border-[1px] border-[#B5C9BDCC] rounded-[16px]  lg:rounded-[32px] lg:px-[54px] lg:py-[48px] px-[20px] py-[20px] green-boxes'>
                                    <div className=''>
                                        <img src={headsetsolid} className='w-[60px]' />
                                        <h3 className='lg:text-[32px] text-[18px]  pt-[24px] lg:pt-[40px]  leading-[18px] lg:leading-[40px] text-[#BAC9C5]'>
                                            Dedicated Support
                                        </h3>
                                        <p className='text-[#A7ABAB] IBMPlexSansRegular pt-[20px] lg:text-[20px] text-[14px] leading-[20px] lg:leading-[32px]'>
                                            Experience unparalleled support with a dedicated account manager available 24/7, 365 days a year. Whether you need assistance, have queries, or require guidance, our account manager is here to ensure you receive timely and expert support whenever you need it. Your success is our priority, and we're committed to being there for you around the clock.                    </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>

            </section>
            {/* 3rd */}
        </>
    );
}

export default BenefitsOfZeroLoss;